# Generated by Django 2.1 on 2018-12-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20181220_1449'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderFoods',
            new_name='OrderFood',
        ),
    ]
