# Generated by Django 2.1 on 2018-12-24 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20181220_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfood',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='webapp.Order', verbose_name='Заказ'),
        ),
    ]
