# Generated by Django 2.1 on 2019-01-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20181224_0848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('change_order_status', 'Может менять статус заказа')]},
        ),
    ]
